version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    # No need to expose the port to the host if only accessed via ngrok
    # you can keep the "ports" section if you want local access too.

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    # Same as backend, you can remove the "ports" if you only need ngrok access.

  ngrok-backend:
    image: ngrok/ngrok:latest
    container_name: ngrok-backend
    command: http backend:8000 --domain ${NGROK_BACKEND_DOMAIN}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_BACKEND_AUTHTOKEN}
    depends_on:
      - backend
    networks:
      - app-network

  ngrok-frontend:
    image: ngrok/ngrok:latest
    container_name: ngrok-frontend
    command: http frontend:3000 --domain ${NGROK_FRONTEND_DOMAIN}
    environment:
      - NGROK_AUTHTOKEN=${NGROK_FRONTEND_AUTHTOKEN}
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge